make gcc: demo CMakeLists.txt *without* SX toolchain

diff --git a/dev-cmake-sx/Makefile b/dev-cmake-sx/Makefile
--- a/dev-cmake-sx/Makefile
+++ b/dev-cmake-sx/Makefile
@@ -1,4 +1,4 @@
-.PHONY: all example tarball rel dbg clean realclean
+.PHONY: all example tarball rel dbg clean realclean gcc
 all: example tarball
 	@echo "You can also make debugging targets: help dbg rel"
 	@echo "to see if cmake -DCMAKE_BUILD_TYPE=xxx works"
@@ -17,10 +17,23 @@ example:
 tarball:
 	tar czf sx-cmake-support.tar.gz Platform cmake cmake.sh
 
+gcc:
+	rm -rf build-$@ $@.err && mkdir build-$@
+	echo "cmake with NO toolchain into build-$@/ ..."
+	ls -l build-$@
+	( cd build-$@ && cmake -DCMAKE_BUILD_TYPE=Release -Wno-dev .. ) 2>&1 | tee $@.err \
+		|| { echo "Error - cmake: see $@.err and build-$@/"; false; }
+	echo "make in build-$@/ ..."
+	(cd build-$@ && make VERBOSE=1) 2>&1 | tee -a $@.err \
+		|| { echo "Error - build: see $@.err and build-$@/"; false; }
+	if [ -f $@.log ]; then mv $@.log $@.log.bak; fi
+	mv $@.err $@.log
+	echo "OK: $@.log"
+
 rel:
 	rm -rf build-$@ $@.err && mkdir build-$@
 	echo "cmake with sx toolchain into build-$@/ ..."
-	(cd build-$@ && cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/sx.cmake --trace -wno-dev \
+	(cd build-$@ && cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/sx.cmake --trace -Wno-dev \
 		-DCMAKE_BUILD_TYPE=Release .. ) >& $@.err \
 		|| { echo "Error - cmake: see $@.err and build-$@/"; false; }
 	echo "make in build-$@/ ..."
